createaquiz/createaquiz/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.sitemaps.views import (index as site_index_view, sitemap as sitemap_view)
from .sitemaps import sitemaps_dict


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/quiz/')),
    path('quiz/', include('quiz.urls')),
    path('user/', include('user.urls')),

    # Sitemaps
    path('sitemap.xml', site_index_view, {'sitemaps': sitemaps_dict}, name='sitemap'),
    path('sitemap-<section>.xml', sitemap_view, {'sitemaps': sitemaps_dict},
         name='django.contrib.sitemaps.views.sitemap'),
]

# modified from https://docs.djangoproject.com/en/2.2/howto/static-files/#serving-static-files-during-development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # Django debug toolbar
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

createaquiz/quiz/urls.py
from django.urls import path
from quiz import views

urlpatterns = [
    # Plotly charts
    path('plotly/', views.plotly_view, name='quiz_plotly'),

    # Tag URLs
    path('tag/', views.TagListView.as_view(), name='tag_list'),
    path('tag/create/', views.TagCreateView.as_view(), name='tag_create'),
    path('tag/<slug>/', views.TagDetailView.as_view(), name='tag_detail'),
    path('tag/<slug>/update', views.TagUpdateView.as_view(), name='tag_update'),
    path('tag/<slug>/delete', views.TagDeleteView.as_view(), name='tag_delete'),

    # Quiz URLs
    path('', views.QuizListView.as_view(), name='quiz_list'),
    path('create/', views.QuizCreateView.as_view(), name='quiz_create'),
    path('<slug>/', views.QuizDetailView.as_view(), name='quiz_detail'),
    path('<slug>/update/', views.QuizUpdateView.as_view(), name='quiz_update'),
    path('<slug>/delete/', views.QuizDeleteView.as_view(), name='quiz_delete'),
    path('<slug>/begin/', views.quiz_start_view, name='quiz_start'),

    # Question URLs
    path('<quiz_slug>/question/create/', views.QuestionCreateView.as_view(), name='quiz_question_create'),
    path('<quiz_slug>/question/<int:pk>/update/', views.QuestionUpdateView.as_view(), name='quiz_question_update'),
    path('<quiz_slug>/question/<int:pk>/delete/', views.QuestionDeleteView.as_view(), name='quiz_question_delete'),
]

createaquiz/quiz/models.py
from random import shuffle
from django.db import models
from django.shortcuts import reverse
from django.conf import settings
from core.utils import ImageResizeUploadS3


class CustomModel:
    """Common Model inherited by other models."""
    def get_model(self):
        return self.__class__.__name__


class Tag(CustomModel, models.Model):
    name = models.CharField(max_length=31, unique=True)
    slug = models.SlugField(max_length=31, unique=True, help_text='A label for URL config')

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name.title()

    def get_absolute_url(self):
        return reverse('tag_detail', kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('tag_update', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('tag_delete', kwargs={'slug': self.slug})

    def get_parent_url(self):
        return reverse('tag_list')


class Quiz(ImageResizeUploadS3, CustomModel, models.Model):
    name = models.CharField(max_length=63, db_index=True)
    slug = models.SlugField(max_length=63, unique=True, help_text='A label for URL config')
    description = models.TextField()
    pub_date = models.DateField('date published', auto_now_add=True)
    tags = models.ManyToManyField(Tag, blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.SET_NULL, null=True)   # If user deleted, posts are not deleted
    image = models.ImageField(null=True, blank=True, default=None, upload_to='quiz_headers')

    # Maximum size of image allowed without resizing (in pixels)
    max_image_size = (800, 800)

    class Meta:
        ordering = ['name']
        get_latest_by = 'pub_date'
        verbose_name_plural = 'Quizzes'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('quiz_detail', kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('quiz_update', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('quiz_delete', kwargs={'slug': self.slug})

    def get_start_url(self):
        return reverse('quiz_start', kwargs={'slug': self.slug})

    def create_question_url(self):
        return reverse('quiz_question_create', kwargs={'quiz_slug': self.slug})


class Question(CustomModel, models.Model):
    question_text = models.CharField(max_length=200)
    correct_choice = models.CharField(max_length=63)
    incorrect_choice_1 = models.CharField(max_length=63)
    incorrect_choice_2 = models.CharField(max_length=63)
    incorrect_choice_3 = models.CharField(max_length=63)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('question_text', 'quiz')     # The same quiz can't have the same questions

    def __str__(self):
        return self.question_text

    def get_absolute_url(self):
        return reverse('quiz_detail', kwargs={'slug': self.quiz.slug})

    def get_update_url(self):
        return reverse('quiz_question_update', kwargs={'quiz_slug': self.quiz.slug, 'pk': self.pk})

    def get_delete_url(self):
        return reverse('quiz_question_delete', kwargs={'quiz_slug': self.quiz.slug, 'pk': self.pk})

    def get_random_choices(self):
        choice_list = [self.correct_choice,
                       self.incorrect_choice_1,
                       self.incorrect_choice_2,
                       self.incorrect_choice_3]
        shuffle(choice_list)
        return choice_list

createaquiz/templates/base.html
{% load staticfiles %}

<!DOCTYPE HTML>
<!--
	Editorial by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>
			{% block title %}
				CreateAQuiz
				{% if title %}
					- {{ title }}
				{% endif %}
			{% endblock title %}
		</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />

		<!-- CSS and favico -->
			<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
			<link rel="SHORTCUT ICON" href="{% static 'images/favicon.ico' %}">

		<!-- Plotly CDN -->
		<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

		{% block head %}{% endblock %}

	</head>
	<body class="is-preload">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Main -->
					<div id="main">

						<div class="inner">

							<!-- Header -->
								<header id="header">
									<a href="{% url 'quiz_list' %}" class="logo"><strong>Create A Quiz</strong> by Ranajay Das</a>
									<ul class="icons">
										<li><a href="https://github.com/ranajaydas/createaquiz" class="icon brands fa-github"><span class="label">Github</span></a></li>
										<li><a href="https://twitter.com/ranajayonroad" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
										<li><a href="https://facebook.com/ranajayontheroad" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
										<li><a href="https://instagram.com/ranajayontheroad" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
									</ul>
								</header>

							<!-- Section: Main -->
								{% if messages %}
									{% for message in messages %}
										<div class="alert alert-{{ message.tags }}">
											{{ message }}
										</div>
									{% endfor %}
								{% endif %}

								{% block content %}
									This is default content.
								{% endblock content %}

						</div>
					</div>

				<!-- Sidebar -->
					<div id="sidebar">
						<div class="inner">

							<!-- Search -->
								<section id="search" class="alt">
									<form method="get" action="{% url 'quiz_list' %}">
										<input type="text" name="q" id="q" placeholder="Search for quizzes..." value="{{ request.GET.q }}"/>
									</form>
								</section>

							<!-- Menu -->
								<nav id="menu">
									<header class="major">
										<h2>Menu</h2>
									</header>
									<ul>
										<li><a href="{% url 'quiz_list' %}">Quizzes</a></li>
										<li><a href="{% url 'tag_list' %}">Tags</a></li>
										<li><a href="{% url 'quiz_plotly' %}">Plots</a></li>
										{% if user.is_authenticated %}
											<li>
												<span class="opener">Create</span>
												<ul>
													<li><a href="{% url 'quiz_create' %}">New Quiz</a></li>
													{% if perms.tag.add_tag %}
														<li><a href="{% url 'tag_create' %}">New Tag</a></li>
													{% endif %}
												</ul>
											</li>
											<li><a href="{% url 'profile_update' %}">My Profile</a></li>
											<li><a href="{% url 'quiz_list' %}?user={{ user.username }}">My Quizzes</a></li>
											<li><a href="{% url 'logout' %}">Logout</a></li>
										{% else %}
											<li><a href="{% url 'login' %}">Login</a></li>
											<li><a href="{% url 'register' %}">Register</a></li>
										{% endif %}
									</ul>
								</nav>

							<!-- Section: Tech Used -->
								<section>
									<header class="major">
										<h2>Technology Used</h2>
									</header>
									<p>This website was made using:</p>
									<ul class="contact">
										<li class="icon brands fa-python">Django 2.2.8</a></li>
										<li class="icon solid fa-database">PostgreSQL</a></li>
										<li class="icon brands fa-html5">HTML + CSS</li>
									</ul>
								</section>

							<!-- Section: Contact -->
								<section>
									<header class="major">
										<h2>Get in touch</h2>
									</header>
									<p>Hi! I am Ranajay Das from Ranajay On The Road. This website was created while I was traveling through Lake Ohrid, North Macedonia in 2019. </p>
									<ul class="contact">
										<li class="icon solid fa-blog"><a href="https://ranajayontheroad.com">Ranajay On The Road</a></li>
										<li class="icon solid fa-home">Somewhere On The Road,<br>Earth</li>
									</ul>
								</section>

							<!-- Footer -->
								<footer id="footer">
									<p><a href="{% url 'sitemap' %}" target="_blank" class="icon solid fa-sitemap"> Sitemap</a></p>
									<p class="copyright">&copy; Create A Quiz. All rights reserved.<br>Design: <a href="https://html5up.net">HTML5 UP</a>.</p>
								</footer>

						</div>
					</div>

			</div>

		<!-- Scripts -->
			<script src="{% static 'assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'assets/js/browser.min.js' %}"></script>
			<script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
			<script src="{% static 'assets/js/util.js' %}"></script>
			<script src="{% static 'assets/js/main.js' %}"></script>
			<!-- Statcounter -->
			<script type="text/javascript">
				var sc_project=12157392;
				var sc_invisible=1;
				var sc_security="7748c790";
			</script>
			<script type="text/javascript" src="https://www.statcounter.com/counter/counter.js" async></script>
			<noscript><div class="statcounter"><a title="Web Analytics Made Easy - StatCounter" href="https://statcounter.com/" target="_blank"><img class="statcounter" src="https://c.statcounter.com/12157392/0/7748c790/1/" alt="Web Analytics Made Easy -StatCounter"></a></div></noscript>
	</body>
</html>